name: ReVanced YouTube Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Required Packages
      run: |
        sudo apt update
        sudo apt install -y git openjdk-17-jdk wget python3 unzip

    - name: Clone Revancify
      run: |
        git clone https://github.com/decipher3114/Revancify.git

    - name: Run Revancify
      run: |
        cd Revancify
        chmod +x revancify.py
        python3 revancify.py -yt

    - name: Upload Patched APK
      uses: actions/upload-artifact@v4
      with:
        name: YouTube-ReVanced
        path: Revancify/output/*.apk


