name: Patch YouTube with Revancify

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git openjdk-17-jdk wget python3 python3-pip unzip
        pip install -r https://raw.githubusercontent.com/decipher3114/Revancify/main/requirements.txt

    - name: Clone Revancify
      run: |
        git clone https://github.com/decipher3114/Revancify.git
        cd Revancify
        python3 revancify.py -yt

    - name: Upload Patched APK
      uses: actions/upload-artifact@v4
      with:
        name: YouTube-ReVanced
        path: Revancify/output/*.apk

