name: ReVanced Automation

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 2 * * *'  # Daily at 2AM UTC

jobs:
  revanced:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl jq

    - name: Run patch script
      run: bash .revanced-workflow/patch.sh

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
       files: revanced.apk
        tag_name: revanced-latest
        name: ReVanced Patched YouTube
        body: "Latest patched YouTube with ReVanced"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
